# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssfile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
