# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css_app', '0002_cssfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssfile',
            name='css_text',
            field=models.CharField(max_length=700),
        ),
    ]
