# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css_app', '0003_auto_20161204_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssfile',
            name='description',
            field=models.TextField(default='default description', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cssfile',
            name='css_text',
            field=models.TextField(),
        ),
    ]
