# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css_app', '0004_auto_20161204_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssfile',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
